"""user_profile_fields

Revision ID: 005378833dd8
Revises: 80c694b3b19e
Create Date: 2026-02-20 06:48:59.557256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005378833dd8'
down_revision: Union[str, None] = '80c694b3b19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('worker_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hire_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_profiles', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('hire_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('bio')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
