"""schedule_shifts

Revision ID: 3767d221eab1
Revises: 005378833dd8
Create Date: 2026-02-20 07:01:52.096630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3767d221eab1'
down_revision: Union[str, None] = '005378833dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_shifts',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('needed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'cancelled', name='sched_shift_status'), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_ts > start_ts', name='ck_sched_shift_end_after_start'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_shifts', schema=None) as batch_op:
        batch_op.create_index('ix_sched_shifts_biz_window', ['business_id', 'start_ts', 'end_ts'], unique=False)

    op.create_table('schedule_assignments',
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'confirmed', 'declined', 'no_show', name='sched_assignment_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['schedule_shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'membership_id', name='uq_sched_assignment')
    )
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_sched_assignment_membership', ['membership_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_sched_assignment_membership')

    op.drop_table('schedule_assignments')
    with op.batch_alter_table('schedule_shifts', schema=None) as batch_op:
        batch_op.drop_index('ix_sched_shifts_biz_window')

    op.drop_table('schedule_shifts')
    # ### end Alembic commands ###
