"""hkops_tables

Revision ID: 432688e91336
Revises: d37cc8959592
Create Date: 2026-02-26 07:46:44.445027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432688e91336'
down_revision: Union[str, None] = 'd37cc8959592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hk_task_types',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('requires_inspection', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hk_task_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hk_task_types_business_id'), ['business_id'], unique=False)

    op.create_table('hk_rooms',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('wing', sa.String(length=50), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('dirty', 'clean', 'inspected', 'out_of_order', 'do_not_disturb', name='roomstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hk_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hk_rooms_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hk_rooms_location_id'), ['location_id'], unique=False)

    op.create_table('hk_tasks',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('task_type_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', 'flagged', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='taskpriority'), nullable=False),
    sa.Column('scheduled_date', sa.String(length=20), nullable=True),
    sa.Column('scheduled_start', sa.String(length=10), nullable=True),
    sa.Column('scheduled_end', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supervisor_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['hk_rooms.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['hk_task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hk_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hk_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_hk_tasks_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hk_tasks_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hk_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hk_tasks_task_type_id'), ['task_type_id'], unique=False)

    op.create_table('hk_inspections',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('inspector_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', 'conditional', name='inspectionresult'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['hk_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('hk_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hk_inspections_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hk_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hk_inspections_business_id'))

    op.drop_table('hk_inspections')
    with op.batch_alter_table('hk_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hk_tasks_task_type_id'))
        batch_op.drop_index(batch_op.f('ix_hk_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_hk_tasks_room_id'))
        batch_op.drop_index(batch_op.f('ix_hk_tasks_business_id'))
        batch_op.drop_index(batch_op.f('ix_hk_tasks_assigned_to'))

    op.drop_table('hk_tasks')
    with op.batch_alter_table('hk_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hk_rooms_location_id'))
        batch_op.drop_index(batch_op.f('ix_hk_rooms_business_id'))

    op.drop_table('hk_rooms')
    with op.batch_alter_table('hk_task_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hk_task_types_business_id'))

    op.drop_table('hk_task_types')
    # ### end Alembic commands ###
