"""marketplace_swap_coverage_rbac_drift

Revision ID: 4e6e5135dc04
Revises: 78f6a32a1e9c
Create Date: 2026-02-22 23:07:03.539698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6e5135dc04'
down_revision: Union[str, None] = '78f6a32a1e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biz_roles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_biz_roles_location_id', 'locations', ['location_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_job_postings_swap_request_id', 'shift_swap_requests', ['swap_request_id'], ['id'])

    with op.batch_alter_table('membership_location_roles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_mlr_created_by_user_id', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('membership_roles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_mr_created_by_user_id', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('shift_swap_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('pending', 'awaiting_peer', 'approved', 'denied', 'auto_approved', 'withdrawn', 'pending_coverage', 'completed', name='swapstatus'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_swap_coverage_posting', 'job_postings', ['coverage_posting_id'], ['id'], use_alter=True)
        batch_op.create_foreign_key('fk_swap_covered_by_membership', 'memberships', ['covered_by_membership_id'], ['id'])

    with op.batch_alter_table('worker_availability', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_availability', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('shift_swap_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_swap_covered_by_membership', type_='foreignkey')
        batch_op.drop_constraint('fk_swap_coverage_posting', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'awaiting_peer', 'approved', 'denied', 'auto_approved', 'withdrawn', 'pending_coverage', 'completed', name='swapstatus'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('membership_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mr_created_by_user_id', type_='foreignkey')

    with op.batch_alter_table('membership_location_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mlr_created_by_user_id', type_='foreignkey')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_postings_swap_request_id', type_='foreignkey')

    with op.batch_alter_table('biz_roles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_biz_roles_location_id', type_='foreignkey')

    # ### end Alembic commands ###
