"""marketplace

Revision ID: 80c694b3b19e
Revises: cd1e249fe560
Create Date: 2026-02-20 03:15:33.671460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c694b3b19e'
down_revision: Union[str, None] = 'cd1e249fe560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_swap_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('initiator_id', sa.String(), nullable=False),
    sa.Column('peer_worker_id', sa.String(), nullable=True),
    sa.Column('their_shift_date', sa.String(length=20), nullable=True),
    sa.Column('their_shift_start', sa.String(length=10), nullable=True),
    sa.Column('their_shift_end', sa.String(length=10), nullable=True),
    sa.Column('their_shift_ref', sa.String(), nullable=True),
    sa.Column('peer_shift_date', sa.String(length=20), nullable=True),
    sa.Column('peer_shift_start', sa.String(length=10), nullable=True),
    sa.Column('peer_shift_end', sa.String(length=10), nullable=True),
    sa.Column('peer_shift_ref', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'awaiting_peer', 'approved', 'denied', 'auto_approved', 'withdrawn', name='swapstatus'), nullable=False),
    sa.Column('peer_accepted', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['peer_worker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_swap_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_swap_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_swap_requests_initiator_id'), ['initiator_id'], unique=False)

    op.create_table('training_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'withdrawn', name='requeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_requests_worker_id'), ['worker_id'], unique=False)

    op.create_table('job_postings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('posted_by', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.Column('shift_date', sa.String(length=20), nullable=True),
    sa.Column('shift_start', sa.String(length=10), nullable=True),
    sa.Column('shift_end', sa.String(length=10), nullable=True),
    sa.Column('pay_rate', sa.String(length=50), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('open', 'filled', 'cancelled', name='postingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_business_id'), ['business_id'], unique=False)

    op.create_table('shift_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', 'withdrawn', name='requeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_posting_id'), ['posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_requests_worker_id'), ['worker_id'], unique=False)

    op.create_table('swap_permission_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('membership_id', sa.String(), nullable=True),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.Time(), nullable=True),
    sa.Column('window_end', sa.Time(), nullable=True),
    sa.Column('effect', sa.Enum('allow', 'deny', name='swapruleeffect'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swap_permission_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swap_permission_rules_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_permission_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swap_permission_rules_business_id'))

    op.drop_table('swap_permission_rules')
    with op.batch_alter_table('shift_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_requests_worker_id'))
        batch_op.drop_index(batch_op.f('ix_shift_requests_posting_id'))
        batch_op.drop_index(batch_op.f('ix_shift_requests_business_id'))

    op.drop_table('shift_requests')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_business_id'))

    op.drop_table('job_postings')
    with op.batch_alter_table('training_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_requests_worker_id'))
        batch_op.drop_index(batch_op.f('ix_training_requests_business_id'))

    op.drop_table('training_requests')
    with op.batch_alter_table('shift_swap_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_swap_requests_initiator_id'))
        batch_op.drop_index(batch_op.f('ix_shift_swap_requests_business_id'))

    op.drop_table('shift_swap_requests')
    # ### end Alembic commands ###
