"""add messaging tables

Revision ID: cbd29a293ca6
Revises: e6d8188d098b
Create Date: 2026-02-20 14:19:36.847847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd29a293ca6'
down_revision: Union[str, None] = 'e6d8188d098b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_api_keys',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('channel_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('msg_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_msg_api_keys_business_id'), ['business_id'], unique=False)

    op.create_table('msg_channels',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('announcement', 'group', 'direct', name='channel_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('msg_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_msg_channels_business_id'), ['business_id'], unique=False)

    op.create_table('msg_channel_members',
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['msg_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'user_id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channel_member')
    )
    op.create_table('msg_messages',
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('user', 'api_key', name='message_source'), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['msg_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('msg_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_msg_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_msg_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_msg_messages_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_msg_messages_expires_at'))
        batch_op.drop_index(batch_op.f('ix_msg_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_msg_messages_channel_id'))

    op.drop_table('msg_messages')
    op.drop_table('msg_channel_members')
    with op.batch_alter_table('msg_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_msg_channels_business_id'))

    op.drop_table('msg_channels')
    with op.batch_alter_table('msg_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_msg_api_keys_business_id'))

    op.drop_table('msg_api_keys')
    # ### end Alembic commands ###
