"""add_parent_id_to_locations

Revision ID: d37cc8959592
Revises: 4e6e5135dc04
Create Date: 2026-02-25 03:40:01.666907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37cc8959592'
down_revision: Union[str, None] = '4e6e5135dc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_locations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key('fk_locations_parent_id', 'locations', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_locations_parent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_locations_parent_id'))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
